stages:
 - deploy
deploy:
 stage: deploy
 script:
 - apt-get update -y
 - apt-get install -y sshpass
 - sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP 'cd /Mymoviesapi && git pull origin main && pm2 restart Mymoviesapi'
only:
 - master